  $ ../test-error.sh *.png
  Testing xc1n0g08.png
  Corrupted image: Unsupported combination of colour type 1 with bit depth 8....
  Testing xc9n2c08.png
  Corrupted image: Unsupported combination of colour type 9 with bit depth 8....
  Testing xcrn0g04.png
  Corrupted image: Corrupted header....
  Testing xcsn0g01.png
  Corrupted image: CRC error....
  Testing xd0n2c08.png
  Corrupted image: Unsupported combination of colour type 2 with bit depth 0....
  Testing xd3n2c08.png
  Corrupted image: Unsupported combination of colour type 2 with bit depth 3....
  Testing xd9n2c08.png
  Corrupted image: Unsupported combination of colour type 2 with bit depth 63....
  Testing xdtn0g01.png
  Corrupted image: PNG.Zlib:Unexpected end of input.
  Testing xhdn0g08.png
  Corrupted image: CRC error....
  Testing xlfn0g04.png
  Corrupted image: Corrupted header....
  Testing xs1n0g01.png
  Corrupted image: Corrupted header....
  Testing xs2n0g01.png
  Corrupted image: Invalid PNG header....
  Testing xs4n0g01.png
  Corrupted image: Invalid PNG header....
  Testing xs7n0g01.png
  Corrupted image: Corrupted header....
  [1]
