on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: [ 4.14.2, 5.0.0, 5.1.1, 5.2.1, 5.3.0 ]
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checking out the repository"
        uses: actions/checkout@v4
      - name: "Setting up opam..."
        uses: avsm/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          opam-disable-sandboxing: true
          cache-prefix: ocaml-${{ matrix.ocaml-version }}
      - run: sudo apt-get install imagemagick
      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
